### ISSUE TITLE
Snap should install 64-bit julia (on 64-bit OS)

### ISSUE THREAD

**Issue by PallHaraldsson** [mrcinv/julia-snap#2]
Hi,

I noticed your snap, and tried it. FYI: As with the official snap, it's only 32-bit, and that has a problem with some software.

**Comment by mrcinv** [comment]
Indeed, thank you for noticing. The snap has some confusing syntax for specifying different architectures, so it only build it on i386 and claim it runs everywhere.

**Comment by PallHaraldsson** [comment]
Thanks, I see it installs now amd64. And I see the file for how it's done. I just have no idea where the official snap is. They should do the same, update to at least 1.0.5 (it's currently 1.0.4) and 64-bit, or later:

FYI: 1.4.2 is out, that you may want to support (with e.g. 2x faster Zlib decoding). I've been thinking 1.5 is around the corner for some time now, if you want to wait for that (1.4.2 might be a hint it's coming, as a backport to older is one of the last hings they do before a release, but still it would only be an RC1 for 1.5).

**Comment by mrcinv** [comment]
The official snap is not maintained as far as I know. I'll bump the version to 1.4.2
